version: '3.8'

services:
  openmsi_processor:
    build:
      context: .  # The directory containing your Dockerfile
    volumes:
      - /srv/hemi01-j01/EZOpenMSIStream/config.config:/home/openmsi/config  # Mount local config folder to container
      - ./output_dir:/home/openmsi/ALPSS/ALPSS/output_dir  # Mount local output_dir to container
      - ./out_files_dir:/home/openmsi/ALPSS/ALPSS/out_files_dir  # Mount local out_files_dir to container
    command: >
      python ALPSS/alpss_stream_processor.py
      --topic_name pdv_data_stieff
      --config /home/openmsi/config
      --output_dir ALPSS/output_dir
      --out_files_dir ALPSS/out_files_dir
      --mode disk